Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
ds.isel(Time=0).SNOW.plot()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[12], line 1[0m
[0;32m----> 1[0m [43mds[49m[38;5;241;43m.[39;49m[43misel[49m[43m([49m[43mTime[49m[38;5;241;43m=[39;49m[38;5;241;43m0[39;49m[43m)[49m[38;5;241;43m.[39;49m[43mSNOW[49m[38;5;241;43m.[39;49m[43mplot[49m[43m([49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/xarray/plot/accessor.py:46[0m, in [0;36mDataArrayPlotAccessor.__call__[0;34m(self, **kwargs)[0m
[1;32m     44[0m [38;5;129m@functools[39m[38;5;241m.[39mwraps(dataarray_plot[38;5;241m.[39mplot, assigned[38;5;241m=[39m([38;5;124m"[39m[38;5;124m__doc__[39m[38;5;124m"[39m, [38;5;124m"[39m[38;5;124m__annotations__[39m[38;5;124m"[39m))
[1;32m     45[0m [38;5;28;01mdef[39;00m [38;5;21m__call__[39m([38;5;28mself[39m, [38;5;241m*[39m[38;5;241m*[39mkwargs) [38;5;241m-[39m[38;5;241m>[39m Any:
[0;32m---> 46[0m     [38;5;28;01mreturn[39;00m [43mdataarray_plot[49m[38;5;241;43m.[39;49m[43mplot[49m[43m([49m[38;5;28;43mself[39;49m[38;5;241;43m.[39;49m[43m_da[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/xarray/plot/dataarray_plot.py:312[0m, in [0;36mplot[0;34m(darray, row, col, col_wrap, ax, hue, subplot_kws, **kwargs)[0m
[1;32m    308[0m     plotfunc [38;5;241m=[39m hist
[1;32m    310[0m kwargs[[38;5;124m"[39m[38;5;124max[39m[38;5;124m"[39m] [38;5;241m=[39m ax
[0;32m--> 312[0m [38;5;28;01mreturn[39;00m [43mplotfunc[49m[43m([49m[43mdarray[49m[43m,[49m[43m [49m[38;5;241;43m*[39;49m[38;5;241;43m*[39;49m[43mkwargs[49m[43m)[49m

File [0;32m/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/xarray/plot/dataarray_plot.py:1517[0m, in [0;36m_plot2d.<locals>.newplotfunc[0;34m(***failed resolving arguments***)[0m
[1;32m   1513[0m [38;5;28;01mif[39;00m darray[38;5;241m.[39mndim [38;5;241m==[39m [38;5;241m0[39m [38;5;129;01mor[39;00m darray[38;5;241m.[39msize [38;5;241m==[39m [38;5;241m0[39m:
[1;32m   1514[0m     [38;5;66;03m# TypeError to be consistent with pandas[39;00m
[1;32m   1515[0m     [38;5;28;01mraise[39;00m [38;5;167;01mTypeError[39;00m([38;5;124m"[39m[38;5;124mNo numeric data to plot.[39m[38;5;124m"[39m)
[0;32m-> 1517[0m plt [38;5;241m=[39m [43mimport_matplotlib_pyplot[49m[43m([49m[43m)[49m
[1;32m   1519[0m [38;5;28;01mif[39;00m (
[1;32m   1520[0m     plotfunc[38;5;241m.[39m[38;5;18m__name__[39m [38;5;241m==[39m [38;5;124m"[39m[38;5;124msurface[39m[38;5;124m"[39m
[1;32m   1521[0m     [38;5;129;01mand[39;00m [38;5;129;01mnot[39;00m kwargs[38;5;241m.[39mget([38;5;124m"[39m[38;5;124m_is_facetgrid[39m[38;5;124m"[39m, [38;5;28;01mFalse[39;00m)
[1;32m   1522[0m     [38;5;129;01mand[39;00m ax [38;5;129;01mis[39;00m [38;5;129;01mnot[39;00m [38;5;28;01mNone[39;00m
[1;32m   1523[0m ):
[1;32m   1524[0m     [38;5;28;01mimport[39;00m [38;5;21;01mmpl_toolkits[39;00m

File [0;32m/usr/share/miniconda3/envs/cookbook-dev/lib/python3.10/site-packages/xarray/plot/utils.py:61[0m, in [0;36mimport_matplotlib_pyplot[0;34m()[0m
[1;32m     59[0m [38;5;250m[39m[38;5;124;03m"""import pyplot"""[39;00m
[1;32m     60[0m [38;5;66;03m# TODO: This function doesn't do anything (after #6109), remove it?[39;00m
[0;32m---> 61[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[1;32m     63[0m [38;5;28;01mreturn[39;00m plt

[0;31mModuleNotFoundError[0m: No module named 'matplotlib'
ModuleNotFoundError: No module named 'matplotlib'

